'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Brain, Zap, Target, Trophy, ArrowRight } from 'lucide-react';
import { supabase } from '../lib/supabaseClient';

export default function Home() {
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => {
      setUser(data.user);
    });

    const { data: listener } = supabase.auth.onAuthStateChange(
      (_event, session) => {
        setUser(session?.user ?? null);
      }
    );

    return () => {
      listener.subscription.unsubscribe();
    };
  }, []);

  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Questions',
      description:
        'Get custom questions generated by advanced AI for any topic you choose.',
    },
    {
      icon: Target,
      title: 'Adaptive Difficulty',
      description:
        'Choose from easy, medium, or hard difficulty levels that match your skill.',
    },
    {
      icon: Zap,
      title: 'Instant Results',
      description:
        'Get immediate feedback with detailed explanations for every question.',
    },
    {
      icon: Trophy,
      title: 'Track Progress',
      description:
        'Monitor your learning journey and see how you improve over time.',
    },
  ];

  return (
    <div className="min-h-screen bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-indigo-100 via-white to-purple-100">
      {/* HERO SECTION */}
      <section className="pt-20 pb-16 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
        {/* Glow background */}
        <div className="absolute inset-0 -z-10 bg-gradient-to-br from-primary-100/40 via-transparent to-purple-200/40 blur-3xl" />

        <div className="max-w-7xl mx-auto text-center">
          <div className="flex justify-center mb-8">
            <div className="flex items-center space-x-3 bg-white/80 backdrop-blur rounded-full px-6 py-3 shadow-lg">
              <Brain className="h-8 w-8 text-primary-600" />
              <span className="text-2xl font-bold text-gray-900">
                Quiz.AI
              </span>
            </div>
          </div>

          <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
            Master Any Topic with
            <span className="text-primary-600 block">
              AI-Powered Quizzes
            </span>
          </h1>

          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
            Challenge yourself with personalized quizzes generated by artificial
            intelligence. Learn faster, retain more, and track your progress.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link
              href="/setup"
              className="btn-primary inline-flex items-center text-lg px-8 py-4"
            >
              Start Learning Now
              <ArrowRight className="ml-2 h-5 w-5" />
            </Link>

            {!user ? (
              <Link
                href="/auth"
                className="btn-secondary inline-flex items-center text-lg px-8 py-4"
              >
                Sign Up Free
              </Link>
            ) : (
              <Link
                href="/profile"
                className="btn-secondary inline-flex items-center text-lg px-8 py-4"
              >
                Go to Dashboard
              </Link>
            )}
          </div>

          {user && (
            <p className="mt-4 text-gray-600">
              Welcome back 👋
            </p>
          )}
        </div>
      </section>

      {/* FEATURES SECTION */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-gradient-to-b from-white to-gray-50">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Why Choose Quiz.AI?
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Our AI-powered platform adapts to your learning style and helps
              you master any subject efficiently.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div
                key={index}
                className="card text-center bg-white/80 backdrop-blur hover:shadow-2xl transition-all"
              >
                <div className="flex justify-center mb-4">
                  <div className="p-3 bg-primary-100 rounded-full">
                    <feature.icon className="h-8 w-8 text-primary-600" />
                  </div>
                </div>

                <h3 className="text-xl font-semibold text-gray-900 mb-2">
                  {feature.title}
                </h3>
                <p className="text-gray-600">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA SECTION */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-gradient-to-br from-primary-600 via-indigo-600 to-purple-600">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
            Ready to Transform Your Learning?
          </h2>

          <p className="text-xl text-primary-100 mb-8">
            Join learners who are already using AI to accelerate their education.
          </p>

          <Link
            href="/setup"
            className="bg-white text-primary-600 hover:bg-gray-100 font-semibold py-4 px-8 rounded-lg text-lg inline-flex items-center transition"
          >
            Start Your Journey With Your First Quiz
            <ArrowRight className="ml-2 h-5 w-5" />
          </Link>
        </div>
      </section>
    </div>
  );
}
